name: .NET Core Audit

on:
  push:
    branches:
      - main
      - test_before_prod
  pull_request:
    branches:
      - main

jobs:


  NodeJSAudit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout librairies
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and run audit in Web Site folder
      run: |
        cd frontend
        npm install
        npm audit


  DotnetAudit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout librairies
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies and run audit in Api Server
      run: |
        cd backend
        dotnet restore
        dotnet list package --vulnerable

    - name: Build Api Server
      run: |
        cd backend
        dotnet build

     - name: Unit Testing Api Server
       run: |
        cd backend
        dotnet test